app:
  jwt:
    secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
    expiration-in-ms: 3600000
    refresh-expiration-in-ms: 86400000

spring:
#  main:
#    allow-circular-references: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.49.2:32358/samplecrud
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    generate-ddl: true
    show-sql: true
